import { createHash } from "node:crypto";
import { z } from "zod";

import { answerChoiceSchema, MAX_EXPRESSIONS, type AnswerChoice } from "./solver-schema";
import { methodSchema, type Method } from "./strategy-selection";
import { TECHNIQUE_IDS } from "./technique-vocabulary";

/**
 * Determinism cache: the same problem returns the same methods, the same order,
 * and the same default every time.
 *
 *   cacheKey = sha256(normalized problem text + choices) + "." + promptConfigVersion
 *
 * The problem key comes from the extracted text, never raw image bytes, so a
 * differently cropped screenshot of the same problem maps to the same entry.
 * An identical re-upload (the same image bytes, or the same problem text)
 * skips even the extraction call: its input hash maps straight to the key. promptConfigVersion hashes everything that shapes
 * a result, so improvements always reach previously cached problems.
 */

export const CACHE_ENTRY_VERSION = 1;

function sha256(text: string): string {
  return createHash("sha256").update(text).digest("hex");
}

/**
 * Transcription-invariant text: the same problem transcribed twice with
 * different spacing, Unicode operators, or superscript styles normalizes to
 * the same string. Content (digits, letters, operators, punctuation) is kept.
 */
export function normalizeProblemText(text: string): string {
  return text
    .replace(/²/g, "^2")
    .replace(/³/g, "^3")
    .normalize("NFKC")
    .replace(/[−–—]/g, "-")
    .replace(/[×·⋅∙]/g, "*")
    .replace(/÷/g, "/")
    .replace(/≤/g, "<=")
    .replace(/≥/g, ">=")
    .replace(/≠/g, "!=")
    .replace(/π/g, "pi")
    .replace(/[“”]/g, '"')
    .replace(/[‘’]/g, "'")
    .replace(/\^\{([^{}]+)\}/g, "^$1")
    .toLowerCase()
    .replace(/\s+/g, "");
}

export function problemKey(question: string, choices: readonly AnswerChoice[] | null): string {
  return sha256(
    JSON.stringify({
      question: normalizeProblemText(question),
      choices: choices?.map((choice) => [choice.label.trim().toUpperCase(), normalizeProblemText(choice.text)]) ?? null,
    }),
  );
}

export function cacheKeyFor(key: string, promptConfigVersion: string): string {
  return `${key}.${promptConfigVersion}`;
}

/** The exact submitted input: image bytes, or the problem text and choices. */
export function inputHash(input: Uint8Array | { problem: string; choices: readonly string[] | null }): string {
  const hash = createHash("sha256");
  if (input instanceof Uint8Array) hash.update("image:").update(input);
  else hash.update(`text:${JSON.stringify([input.problem, input.choices])}`);
  return hash.digest("hex");
}

/**
 * Everything that shapes a cached result: both prompts, the strategy library,
 * the gold solutions, the cost weights, the technique vocabulary, the
 * response schemas, and the model. Any change yields a new version, so the
 * next solve of a cached problem regenerates.
 */
export function promptConfigVersion(parts: {
  candidateInstructions: string;
  explanationInstructions: string;
  strategyLibrary: string;
  goldSolutions: string;
  candidatePrompt: string;
  costWeights: unknown;
  vocabulary: unknown;
  schemas: unknown;
  model: string;
}): string {
  return sha256(JSON.stringify(parts)).slice(0, 24);
}

// The fixed-length purposes list comes last: ahead of other fields, models
// were observed to spill readAnswer and steps into it as extra strings.
export const explanationSchema = z
  .object({
    why: z.string().min(1).max(1200),
    // Any step the student does by hand beside typing the rows, named and
    // explained; null for a pure-Desmos method. Defaults for entries cached before it existed.
    handMath: z.string().max(600).nullable().default(null),
    readAnswer: z.string().max(1000).nullable(),
    steps: z.array(z.string().min(1).max(800)).max(5),
    purposes: z.array(z.string().min(1).max(600)).max(16),
  })
  .strict();
export type Explanation = z.infer<typeof explanationSchema>;

export const cacheEntrySchema = z.object({
  version: z.literal(CACHE_ENTRY_VERSION),
  cacheKey: z.string().min(1),
  promptConfigVersion: z.string().min(1),
  question: z.string(),
  choices: z.array(answerChoiceSchema).nullable(),
  structure: z.string().nullable(),
  // Empty only for a Desmos retry that produced no usable method.
  methods: z.array(methodSchema),
  winnerId: z.string(),
  modelPreference: z.enum(TECHNIQUE_IDS).nullable(),
  /** Set on the entry generated by the one Desmos retry: the key of the entry it replaced. */
  retryOf: z.string().nullable().default(null),
  createdAt: z.string(),
});
export type CacheEntry = z.infer<typeof cacheEntrySchema>;
export type CacheEntryInput = z.input<typeof cacheEntrySchema>;

/**
 * A pre-flight verdict for one method, as a browser's hidden Desmos instance
 * reported it. Cached alongside the entry so a cache hit never re-runs
 * candidate pre-flight, re-selection, or the retry. Written first-writer-wins
 * like explanations: a later report never overwrites a stored verdict.
 */
export const preflightRecordSchema = z.discriminatedUnion("status", [
  z.object({ status: z.literal("clean") }).strict(),
  z
    .object({
      status: z.literal("error"),
      errors: z
        .array(z.object({ row: z.number().int().min(1).max(MAX_EXPRESSIONS), message: z.string().max(300) }).strict())
        .min(1)
        .max(MAX_EXPRESSIONS),
    })
    .strict(),
]);
export type PreflightRecord = z.infer<typeof preflightRecordSchema>;

/** Where the one Desmos retry for an entry is stored. */
export function retryCacheKey(cacheKey: string): string {
  return `${cacheKey}.desmos-retry`;
}

export function eligibleMethods(entry: CacheEntry): Method[] {
  return entry.methods.filter((method) => method.rejected === null);
}

export function findMethod(entry: CacheEntry, methodId: string): Method | null {
  return eligibleMethods(entry).find((method) => method.id === methodId) ?? null;
}

/**
 * Writes are first-writer-wins: two concurrent solves of the same problem
 * both end up returning whichever entry (or explanation) was stored first.
 */
export interface SolveCache {
  lookupInput(inputHash: string, promptConfigVersion: string): Promise<string | null>;
  rememberInput(inputHash: string, promptConfigVersion: string, cacheKey: string): Promise<void>;
  getEntry(cacheKey: string): Promise<CacheEntry | null>;
  putEntry(entry: CacheEntry): Promise<CacheEntry>;
  getExplanation(cacheKey: string, methodId: string): Promise<Explanation | null>;
  putExplanation(cacheKey: string, methodId: string, explanation: Explanation): Promise<Explanation>;
  getPreflight(cacheKey: string): Promise<Record<string, PreflightRecord>>;
  putPreflight(cacheKey: string, methodId: string, record: PreflightRecord): Promise<PreflightRecord>;
}

function parseEntry(value: unknown): CacheEntry | null {
  const parsed = cacheEntrySchema.safeParse(value);
  return parsed.success ? parsed.data : null;
}

function parseExplanation(value: unknown): Explanation | null {
  const parsed = explanationSchema.safeParse(value);
  return parsed.success ? parsed.data : null;
}

function parsePreflight(value: unknown): PreflightRecord | null {
  const parsed = preflightRecordSchema.safeParse(value);
  return parsed.success ? parsed.data : null;
}

/**
 * Process-local cache for tests, the eval harness, and the server's fallback
 * tier (no persistence). `limit` bounds each table; the oldest key goes first.
 */
export function createMemorySolveCache(options: { limit?: number } = {}): SolveCache & { size(): { entries: number; explanations: number; inputs: number; preflight: number } } {
  const inputs = new Map<string, string>();
  const entries = new Map<string, CacheEntry>();
  const explanations = new Map<string, Explanation>();
  const preflight = new Map<string, Map<string, PreflightRecord>>();
  const clone = <T>(value: T): T => structuredClone(value);
  const limit = options.limit ?? Infinity;
  /** First writer wins: returns the stored value, inserting `value` only when the key is new. */
  const put = <T>(map: Map<string, T>, key: string, value: T): T => {
    if (!map.has(key)) {
      map.set(key, value);
      if (map.size > limit) map.delete(map.keys().next().value!);
    }
    return map.get(key)!;
  };
  return {
    async lookupInput(hash, version) {
      return inputs.get(`${hash}.${version}`) ?? null;
    },
    async rememberInput(hash, version, cacheKey) {
      put(inputs, `${hash}.${version}`, cacheKey);
    },
    async getEntry(cacheKey) {
      const entry = entries.get(cacheKey);
      return entry ? clone(entry) : null;
    },
    async putEntry(entry) {
      return clone(put(entries, entry.cacheKey, clone(entry)));
    },
    async getExplanation(cacheKey, methodId) {
      const explanation = explanations.get(`${cacheKey} ${methodId}`);
      return explanation ? clone(explanation) : null;
    },
    async putExplanation(cacheKey, methodId, explanation) {
      return clone(put(explanations, `${cacheKey} ${methodId}`, clone(explanation)));
    },
    async getPreflight(cacheKey) {
      return clone(Object.fromEntries(preflight.get(cacheKey) ?? []));
    },
    async putPreflight(cacheKey, methodId, record) {
      const records = put(preflight, cacheKey, new Map<string, PreflightRecord>());
      if (!records.has(methodId)) records.set(methodId, clone(record));
      return clone(records.get(methodId)!);
    },
    size() {
      return {
        entries: entries.size,
        explanations: explanations.size,
        inputs: inputs.size,
        preflight: [...preflight.values()].reduce((sum, records) => sum + records.size, 0),
      };
    },
  };
}

/** The subset of a Supabase client this cache uses; see the solve_cache migration. */
type SupabaseLike = {
  from(table: string): {
    select(columns: string): {
      eq(column: string, value: string): PromiseLike<{ data: unknown; error: unknown }> & {
        eq(column: string, value: string): { maybeSingle(): PromiseLike<{ data: unknown; error: unknown }> };
        maybeSingle(): PromiseLike<{ data: unknown; error: unknown }>;
      };
    };
    upsert(
      row: Record<string, unknown>,
      options: { onConflict: string; ignoreDuplicates: boolean },
    ): PromiseLike<{ error: unknown }>;
  };
};

/**
 * Backed by the existing Supabase project (tables solve_cache,
 * solve_cache_inputs, solve_cache_explanations, solve_cache_preflight;
 * service role only).
 */
export function createSupabaseSolveCache(client: { from(table: string): unknown }): SolveCache {
  // Narrowed here: comparing the full generated client type is needlessly deep.
  const db = client as unknown as SupabaseLike;
  // PostgREST's code and message (e.g. PGRST205, a table the migration has
  // not created yet) name the fix; they never contain credentials.
  const cause = (error: unknown) => {
    const { code, message } = (error ?? {}) as { code?: unknown; message?: unknown };
    return [code, message].filter((part) => typeof part === "string" && part).join(" ");
  };
  async function one(table: string, filters: [string, string][], columns: string) {
    const [first, second] = filters;
    const query = db.from(table).select(columns).eq(first[0], first[1]);
    const { data, error } = await (second ? query.eq(second[0], second[1]) : query).maybeSingle();
    if (error) throw new Error(`solve cache read failed (${table}): ${cause(error)}`);
    return data as Record<string, unknown> | null;
  }
  async function insert(table: string, row: Record<string, unknown>, conflict: string) {
    const { error } = await db.from(table).upsert(row, { onConflict: conflict, ignoreDuplicates: true });
    if (error) throw new Error(`solve cache write failed (${table}): ${cause(error)}`);
  }
  return {
    async lookupInput(hash, version) {
      const row = await one("solve_cache_inputs", [["input_hash", hash], ["prompt_config_version", version]], "cache_key");
      return typeof row?.cache_key === "string" ? row.cache_key : null;
    },
    async rememberInput(hash, version, cacheKey) {
      await insert("solve_cache_inputs", { input_hash: hash, prompt_config_version: version, cache_key: cacheKey }, "input_hash,prompt_config_version");
    },
    async getEntry(cacheKey) {
      const row = await one("solve_cache", [["cache_key", cacheKey]], "entry");
      return row ? parseEntry(row.entry) : null;
    },
    async putEntry(entry) {
      await insert(
        "solve_cache",
        { cache_key: entry.cacheKey, prompt_config_version: entry.promptConfigVersion, entry },
        "cache_key",
      );
      return (await this.getEntry(entry.cacheKey)) ?? entry;
    },
    async getExplanation(cacheKey, methodId) {
      const row = await one("solve_cache_explanations", [["cache_key", cacheKey], ["method_id", methodId]], "explanation");
      return row ? parseExplanation(row.explanation) : null;
    },
    async putExplanation(cacheKey, methodId, explanation) {
      await insert("solve_cache_explanations", { cache_key: cacheKey, method_id: methodId, explanation }, "cache_key,method_id");
      return (await this.getExplanation(cacheKey, methodId)) ?? explanation;
    },
    async getPreflight(cacheKey) {
      const { data, error } = await db.from("solve_cache_preflight").select("method_id,verdict").eq("cache_key", cacheKey);
      if (error) throw new Error(`solve cache read failed (solve_cache_preflight): ${cause(error)}`);
      const records: Record<string, PreflightRecord> = {};
      for (const row of (data ?? []) as { method_id?: unknown; verdict?: unknown }[]) {
        const record = parsePreflight(row.verdict);
        if (typeof row.method_id === "string" && record) records[row.method_id] = record;
      }
      return records;
    },
    async putPreflight(cacheKey, methodId, record) {
      await insert("solve_cache_preflight", { cache_key: cacheKey, method_id: methodId, verdict: record }, "cache_key,method_id");
      return (await this.getPreflight(cacheKey))[methodId] ?? record;
    },
  };
}

/**
 * A cache outage (unreachable database, migration not yet applied) must never
 * fail a solve. With a `local` tier (the server process's own memory cache),
 * every write also lands there and a read the database cannot answer falls
 * back to it, so within one server a solve can still be found again: a
 * technique switch gets its rows and explanation instead of a "not available"
 * error. Without one, reads miss and writes return what they were given.
 * Either way the solve completes, just without cross-server determinism until
 * the database recovers.
 */
export function withCacheFallback(cache: SolveCache, onError: (operation: string, error: unknown) => void, local?: SolveCache): SolveCache {
  const read = async <T>(operation: string, run: (tier: SolveCache) => Promise<T>, empty: (value: T) => boolean, fallback: T): Promise<T> => {
    try {
      const value = await run(cache);
      if (!local || !empty(value)) return value;
    } catch (error) {
      onError(operation, error);
    }
    return local ? run(local) : fallback;
  };
  const write = async <T>(operation: string, run: (tier: SolveCache) => Promise<T>, fallback: T): Promise<T> => {
    const kept = local ? await run(local) : fallback;
    try {
      return await run(cache);
    } catch (error) {
      onError(operation, error);
      return kept;
    }
  };
  const missing = (value: unknown) => value === null;
  return {
    lookupInput: (hash, version) => read("lookupInput", (tier) => tier.lookupInput(hash, version), missing, null),
    rememberInput: (hash, version, key) => write("rememberInput", (tier) => tier.rememberInput(hash, version, key), undefined),
    getEntry: (key) => read("getEntry", (tier) => tier.getEntry(key), missing, null),
    putEntry: (entry) => write("putEntry", (tier) => tier.putEntry(entry), entry),
    getExplanation: (key, id) => read("getExplanation", (tier) => tier.getExplanation(key, id), missing, null),
    putExplanation: (key, id, explanation) => write("putExplanation", (tier) => tier.putExplanation(key, id, explanation), explanation),
    // Without the table (migration not applied) and without a local tier,
    // verdicts are simply not cached: every client runs pre-flight itself,
    // and nothing unverified is ever shown.
    getPreflight: (key) => read("getPreflight", (tier) => tier.getPreflight(key), (value) => Object.keys(value).length === 0, {}),
    putPreflight: (key, id, record) => write("putPreflight", (tier) => tier.putPreflight(key, id, record), record),
  };
}

/**
 * This server process's fallback tier for the solve cache (see
 * withCacheFallback). Bounded, so a long-running server without the database
 * tables does not grow without limit.
 */
export const processSolveCache = createMemorySolveCache({ limit: 500 });

/** The cache every route uses: Supabase first, this process's memory when Supabase cannot answer. */
export function routeSolveCache(client: { from(table: string): unknown }): SolveCache {
  return withCacheFallback(
    createSupabaseSolveCache(client),
    (operation, error) =>
      console.warn(
        `[desmo:cache] ${operation} failed; using this server's in-memory cache. ${error instanceof Error ? error.message : ""}`.trim(),
      ),
    processSolveCache,
  );
}
